### ISSUE TITLE
代码为什么不开源呢？钱包到底怎么用呢？

### ISSUE THREAD

**Issue by zhangcongrong** [bitfreecash/bitfree#2]

**Comment by VVanaheim** [comment]
去优盾官网看看，优盾的钱包代码是开源的，可以学习和参考用https://www.uduncloud.com/

**Comment by zhangcongrong** [comment]
> 去优盾官网看看，优盾的钱包代码是开源的，可以学习和参考用https://www.uduncloud.com/
